//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinGrove_API.DataClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDrink
    {
        public int DrinkId { get; set; }
        public bool DrinkIsAlcohol { get; set; }
        public int ProductId { get; set; }
    }
}
